### PR TITLE
Add option waitForCommand

### PR DESCRIPTION
**Pull request by crashbell**

### CODE REVIEW

**Comment by buunguyen** [comment]
Can you add a bit more comment to the code to clarify what we're doing and why we're doing it. Pretty important thing when we modify 3rd-party lib.

**Comment by crashbell** [comment]
@buunguyen I added comments.

**Comment by buunguyen** [comment]
Without a proper context, it's hard to understand the implementation. So, we want to take screenshot and send over socket, but why need to wait for command before doing so? Isn't the 'S' enough? And the "on-demand" part, what exactly does it mean and how is it different from other commands.

**Comment by crashbell** [comment]
By default, minicap will run as a streaming server which automatically streams data over socket when any socket connects to. That's too much for us when we only need a screenshot at a time. Using _S_ can help us but that can overheat ADB when all data transferred via ADB (shell command and screenshot data). So we need something that can only give us screenshots when we want and transfer screenshot via TCP socket instead of ADB. _C_ is introduced to fill this gap. With this param, minicap server will hold and wait for a command to take screenshot, that reduces the useless cost. And it's use TCP connection to transfer screenshot, that reduces the pressure on ADB. 

Note: I will pass the above paragraph as a comment for _C_ param.

**Comment by crashbell** [comment]
@buunguyen I have realized you mention 'S' not 's'. Did you mean the skip frame option?

**Comment by buunguyen** [comment]
I mean -s. Please add the comment to the change.

**Comment by crashbell** [comment]
@buunguyen Comment is added, anh.

**Comment by buunguyen** [comment]
Thanks em, LGTM.

**Pull request merged**
